package com.example.maventest.db.mapper;

import com.example.maventest.db.model.Test;
import com.example.maventest.db.model.TestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TESTUSER.TEST
     *
     * @mbggenerated Tue Sep 23 16:35:47 JST 2014
     */
    int countByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TESTUSER.TEST
     *
     * @mbggenerated Tue Sep 23 16:35:47 JST 2014
     */
    int deleteByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TESTUSER.TEST
     *
     * @mbggenerated Tue Sep 23 16:35:47 JST 2014
     */
    int insert(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TESTUSER.TEST
     *
     * @mbggenerated Tue Sep 23 16:35:47 JST 2014
     */
    int insertSelective(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TESTUSER.TEST
     *
     * @mbggenerated Tue Sep 23 16:35:47 JST 2014
     */
    List<Test> selectByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TESTUSER.TEST
     *
     * @mbggenerated Tue Sep 23 16:35:47 JST 2014
     */
    int updateByExampleSelective(@Param("record") Test record, @Param("example") TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TESTUSER.TEST
     *
     * @mbggenerated Tue Sep 23 16:35:47 JST 2014
     */
    int updateByExample(@Param("record") Test record, @Param("example") TestExample example);
}