package com.example.maventest.db.model;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TESTUSER.TEST.ID
     *
     * @mbggenerated Tue Sep 23 16:35:47 JST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TESTUSER.TEST.NAME
     *
     * @mbggenerated Tue Sep 23 16:35:47 JST 2014
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TESTUSER.TEST.ID
     *
     * @return the value of TESTUSER.TEST.ID
     *
     * @mbggenerated Tue Sep 23 16:35:47 JST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TESTUSER.TEST.ID
     *
     * @param id the value for TESTUSER.TEST.ID
     *
     * @mbggenerated Tue Sep 23 16:35:47 JST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TESTUSER.TEST.NAME
     *
     * @return the value of TESTUSER.TEST.NAME
     *
     * @mbggenerated Tue Sep 23 16:35:47 JST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TESTUSER.TEST.NAME
     *
     * @param name the value for TESTUSER.TEST.NAME
     *
     * @mbggenerated Tue Sep 23 16:35:47 JST 2014
     */
    public void setName(String name) {
        this.name = name;
    }
}